[phases.setup]
nixPkgs = ["postgresql_15", "gcc"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
]

[start]
cmd = "gunicorn carpool_project.wsgi:application" 