# Generated by Django 5.0.2 on 2025-03-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="route_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="route_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="route_geometry",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="route_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="route_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="riderequest",
            name="route_geometry",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
