# Generated by Django 5.0.2 on 2025-03-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="riderequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="route_distance",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="route_duration",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="route_geometry",
        ),
        migrations.AddField(
            model_name="riderequest",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
