# Generated by Django 4.2.10 on 2025-04-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_add_driver_name_column"),
        ("rides", "add_driver_name_migration"),
    ]

    operations = []
