# Generated by Django 5.0.2 on 2025-04-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        ('rides', '0002_initial'),
        ('rides', '0003_add_proposed_ride_field'),
        ('rides', '0004_add_driver_name_column'),
        ('rides', '0005_merge_20250408_1726'),
        ('rides', 'add_driver_name_migration'),
    ]

    operations = [
    ]
