# Generated by Django 5.0.2 on 2025-03-27 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_alter_riderequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("RIDE_REQUEST", "Ride Request"),
                    ("REQUEST_ACCEPTED", "Request Accepted"),
                    ("REQUEST_REJECTED", "Request Rejected"),
                    ("RIDE_MATCH", "Ride Match"),
                    ("RIDE_ACCEPTED", "Ride Accepted"),
                    ("RIDE_REJECTED", "Ride Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
