# Generated by Django 5.0.2 on 2025-03-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_notification_sender_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("RIDE_REQUEST", "Ride Request"),
                    ("REQUEST_ACCEPTED", "Request Accepted"),
                    ("REQUEST_REJECTED", "Request Rejected"),
                    ("RIDE_MATCH", "Ride Match"),
                    ("RIDE_ACCEPTED", "Ride Accepted"),
                    ("RIDE_REJECTED", "Ride Rejected"),
                    ("RIDE_CANCELLED", "Ride Cancelled"),
                    ("RIDE_COMPLETED", "Ride Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PendingRideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField()),
                ("dropoff_longitude", models.FloatField()),
                ("departure_time", models.DateTimeField()),
                ("seats_needed", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_ride_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_request",
                        to="rides.riderequest",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_ride_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["departure_time"],
            },
        ),
    ]
