# Generated by Django 5.0.2 on 2025-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0007_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("RIDE_REQUEST", "Ride Request"),
                    ("REQUEST_ACCEPTED", "Request Accepted"),
                    ("REQUEST_REJECTED", "Request Rejected"),
                    ("RIDE_MATCH", "Ride Match"),
                    ("RIDE_ACCEPTED", "Ride Accepted"),
                    ("RIDE_REJECTED", "Ride Rejected"),
                    ("RIDE_CANCELLED", "Ride Cancelled"),
                    ("RIDE_COMPLETED", "Ride Completed"),
                    ("RIDE_PENDING", "Ride Pending"),
                ],
                max_length=20,
            ),
        ),
    ]
