# Generated by Django 5.0.2 on 2025-03-29 18:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0008_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="nearest_dropoff_point",
            field=models.JSONField(
                blank=True,
                help_text="Information about the nearest point on driver's route to rider's destination",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="departure_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 29, 18, 33, 4, 896681, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ride_requests",
                to="rides.ride",
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
