# Generated by Django 4.2.10 on 2025-04-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0007_add_missing_fields"),
    ]

    operations = [
        # Original SQLite PRAGMA commands removed - they were a no-op
        # (all ALTER TABLE statements were commented out)
    ]
