# Generated by Django 4.2.10 on 2025-04-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0007_add_missing_fields"),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - add columns if they don't exist
            """
            PRAGMA foreign_keys=off;
            
            ALTER TABLE rides_riderequest ADD COLUMN departure_time datetime DEFAULT CURRENT_TIMESTAMP;
            ALTER TABLE rides_riderequest ADD COLUMN optimal_pickup_point text NULL;
            ALTER TABLE rides_riderequest ADD COLUMN nearest_dropoff_point text NULL;
            
            PRAGMA foreign_keys=on;
            """,
            # Reverse SQL - No rollback needed since SQLite doesn't support dropping columns
            reverse_sql=""
        ),
    ]
