# Generated by Django 5.0.2 on 2025-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0009_riderequest_nearest_dropoff_point_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="departure_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
