# Generated by Django 4.2.10 on 2025-04-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0008_add_riderequest_fields"),
        ("rides", "0009_fix_riderequest_fields"),
    ]

    operations = []
