# Generated by Django 4.2.10 on 2025-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0009_riderequest_nearest_dropoff_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='optimal_pickup_point',
            field=models.JSONField(blank=True, help_text="Information about the optimal pickup point along driver's route", null=True),
        ),
    ]
