# Generated by Django 4.2.10 on 2025-04-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0011_create_notification_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="price_per_seat",
        ),
    ]
