# Generated by Django 4.2.10 on 2025-04-03 00:57

from django.db import migrations
from django.db.models import JSONField

def noop(apps, schema_editor):
    """
    No operation - just used to mark migration as applied
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_add_optimal_pickup_point'),
    ]

    operations = [
        # Run a dummy function to mark this migration as applied
        migrations.RunPython(noop, noop),
        
        # This explicitly marks the migration 0011 as applied without trying 
        # to create the column again, since it already exists
        migrations.RunSQL(
            "UPDATE django_migrations SET applied = now() WHERE app = 'rides' AND name = '0011_add_optimal_pickup_point';",
            reverse_sql="SELECT 1;"
        ),
    ]
