# Generated by Django 4.2.10 on 2025-04-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0012_remove_price_per_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_pending_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="rides.pendingriderequest",
            ),
        ),
    ]
