# Generated by Django 4.2.10 on 2025-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0013_notification_related_pending_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="distance",
            field=models.FloatField(
                blank=True,
                help_text="Distance between pickup and dropoff in kilometers",
                null=True,
            ),
        ),
    ]
